version: 2.1
jobs:
  TWRP-j4ltejx:
   docker:
      - image: hendramanu/docker-build:build-advanced
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir twrp && cd twrp
            repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1
            repo sync -j$(nproc --all)
            mkdir -p device/samsung && cd device/samsung
            git clone https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME j4ltejx
            cd ../..
            source build/envsetup.sh
            add_lunch_combo omni_j4ltejx-eng
            add_lunch_combo omni_j4ltejx-userdebug
            lunch omni_j4ltejx-userdebug
            mka recoveryimage

workflows:
  version: 2.1
  cooking:
    jobs:
      - TWRP-j4ltejx
